image: atlassian/default-image:4
pipelines:
  default:
    - step:
        runs-on:
          - self.hosted
          - linux2
        name: npm install
        script: 
          - git submodule sync
          - git submodule update --init --recursive
          - cd baserepo
          - npm ci
          - npm run build
