pipeline:
  name: Build npm-install
  identifier: Build_findalternative_npm_install_1705334103911
  projectIdentifier: npminstall
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: npm-install
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: |-
                      cd baserepo
                      npm ci
                      npm run build
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1705332593378
        repoName: findalternative/npm-install
        build: <+input>
