name: npm-install

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: npm install and test 
        run: | 
          cd baserepo
          yarn
          yarn check-all
